# Generated by Django 2.1.7 on 2023-12-05 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231205_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 5, 15, 51, 23, 623170)),
        ),
    ]
